'use strict';
document.body.classList.remove('no-js');
const destinations=[
{id:'ha-long',name:'Vịnh Hạ Long',region:'north',regionName:'Miền Bắc',category:'Biển & đảo',mood:'coast',image:'assets/ha-long.svg',intro:'Một khoảng xanh giữa làn nước yên ả và những đảo đá vôi.',description:'Những đảo đá nối nhau trên mặt vịnh tạo nên một phong cảnh rất riêng. Hạ Long gợi một chuyến đi chậm: nhìn mặt nước, ngắm những mảng xanh và cảm nhận không gian rộng mở.',experiences:['Ngắm cảnh vịnh và các đảo đá','Tìm hiểu đời sống gắn với biển','Ghi lại những khoảnh khắc trên mặt nước'],source:'https://vietnam.travel/vi/places-to-go/northern-vietnam/ha-long'},
{id:'ninh-binh',name:'Ninh Bình',region:'north',regionName:'Miền Bắc',category:'Núi & sông',mood:'nature',image:'assets/ninh-binh.svg',intro:'Dòng sông mềm mại đi qua những miền núi đá trùng điệp.',description:'Ở Ninh Bình, núi đá, đồng xanh và những dòng nước tạo thành một không gian yên bình. Một chuyến khám phá nơi đây có thể bắt đầu bằng cảnh quan Tràng An và những câu chuyện văn hóa địa phương.',experiences:['Khám phá cảnh quan Tràng An','Ngắm núi đá và những dòng sông','Tìm hiểu những dấu ấn văn hóa'],source:'https://vietnam.travel/places-to-go/northern-vietnam/ninh-binh'},
{id:'hoi-an',name:'Hội An',region:'central',regionName:'Miền Trung',category:'Phố & di sản',mood:'culture',image:'assets/hoi-an.svg',intro:'Phố cũ, mái ngói và những sắc đèn đầy thương nhớ.',description:'Phố cổ Hội An lưu giữ những dấu ấn giao thoa văn hóa trong kiến trúc và đời sống. Đi bộ giữa những ngôi nhà cũ, nhìn sắc đèn và lắng nghe một câu chuyện là cách thật nhẹ nhàng để khám phá nơi này.',experiences:['Dạo bước trong không gian phố cổ','Tìm hiểu kiến trúc và di sản','Khám phá đời sống, hàng quán địa phương'],source:'https://vietnam.travel/places-to-go/central-vietnam/hoi-an'},
{id:'hue',name:'Huế',region:'central',regionName:'Miền Trung',category:'Văn hóa & di sản',mood:'culture',image:'assets/hue.svg',intro:'Một miền trầm lắng, nơi ký ức và cảnh sắc cùng lên tiếng.',description:'Huế gắn với những dấu ấn của kinh đô xưa, những công trình di sản và nhịp sống bên dòng sông Hương. Một chuyến đi ở đây là dịp để chậm lại và tìm hiểu những lớp văn hóa của miền đất này.',experiences:['Tìm hiểu không gian di sản','Ghé những công trình kiến trúc cổ','Cảm nhận nhịp sống bên sông Hương'],source:'https://vietnam.travel/places-to-go/central-vietnam/hue'},
{id:'da-lat',name:'Đà Lạt',region:'south',regionName:'Miền Nam',category:'Núi & rừng',mood:'nature',image:'assets/da-lat.svg',intro:'Một miền cao nguyên với hồ nước và những khoảng rừng xanh.',description:'Đà Lạt mang đến một không gian cao nguyên với những khoảng xanh, hồ nước và kiến trúc đặc trưng. Từ một cuộc dạo bộ đến một buổi ngồi yên nhìn cảnh vật, nơi đây gợi nhiều cách để nghỉ ngơi và khám phá.',experiences:['Khám phá những khoảng xanh','Dạo quanh các không gian hồ nước','Tìm hiểu kiến trúc và đời sống địa phương'],source:'https://vietnam.travel/places-to-go/central-vietnam/da-lat'},
{id:'phu-quoc',name:'Phú Quốc',region:'south',regionName:'Miền Nam',category:'Biển & đảo',mood:'coast',image:'assets/phu-quoc.svg',intro:'Thêm một ngày không vội giữa biển xanh và đường chân trời.',description:'Phú Quốc là một điểm đến biển đảo với bờ biển, thiên nhiên và những câu chuyện gắn với đời sống trên đảo. Hãy dành thời gian khám phá, tìm hiểu địa phương và giữ gìn vẻ đẹp của biển.',experiences:['Cảm nhận không gian biển đảo','Tìm hiểu đời sống địa phương','Khám phá thiên nhiên với sự trân trọng'],source:'https://vietnam.travel/places-to-go/southern-vietnam/phu-quoc'}
];
const get=id=>document.getElementById(id), node=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;};
let region='all',mood=null,selected=null,scene=0,toastTimer;
let saved=new Set();try{const stored=JSON.parse(localStorage.getItem('vietnam-trip')||'[]');if(Array.isArray(stored))saved=new Set(stored.filter(id=>destinations.some(place=>place.id===id)));}catch{}
const normalize=text=>text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
function toast(message){get('toast').textContent=message;get('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>get('toast').hidden=true,3500);}
function persist(){get('saved-count').textContent=saved.size;try{localStorage.setItem('vietnam-trip',JSON.stringify([...saved]));return true;}catch{return false;}}
function toggleSave(id){if(saved.has(id))saved.delete(id);else saved.add(id);const kept=persist();render();renderTrip();if(selected?.id===id)updateDetailSave();toast(kept?(saved.has(id)?'Đã lưu miền đất này vào hành trình.':'Đã bỏ điểm đến khỏi hành trình.'):'Trình duyệt không cho lưu trên máy. Hành trình vẫn có trong phiên này.');}
function render(){const query=normalize(get('destination-search').value.trim());const places=destinations.filter(place=>(region==='all'||place.region===region)&&(!mood||place.mood===mood)&&normalize(place.name+' '+place.category).includes(query));const grid=get('destination-grid');grid.replaceChildren();
for(const [index,place]of places.entries()){const card=node('article','destination-card');card.style.animationDelay=`${index*60}ms`;const visual=node('div','destination-visual'),image=node('img');image.src=place.image;image.alt=`Minh họa ${place.name}`;image.loading='lazy';image.width=600;image.height=450;visual.append(image,node('span','destination-badge',place.regionName));const save=node('button','save-destination',saved.has(place.id)?'♥':'♡');save.type='button';save.setAttribute('aria-label',(saved.has(place.id)?'Bỏ lưu ':'Lưu ')+place.name);save.setAttribute('aria-pressed',String(saved.has(place.id)));save.onclick=()=>toggleSave(place.id);visual.append(save);const copy=node('div','destination-copy');copy.append(node('small','',place.category.toUpperCase()),node('h3','',place.name),node('p','',place.intro));const open=node('button','destination-open');open.type='button';open.setAttribute('aria-label','Khám phá '+place.name);open.append(document.createTextNode('Khám phá miền đất'),node('span','','↗'));open.onclick=()=>showDetails(place);copy.append(open);card.append(visual,copy);grid.append(card);}get('search-status').textContent=places.length?`${places.length} điểm đến${mood?' · Đang lọc theo trải nghiệm. Chọn vùng để xem lại tất cả chủ đề.':''}`:'Chưa tìm thấy điểm đến phù hợp. Thử tên khác hoặc chọn Tất cả.';}
function updateDetailSave(){get('detail-save').textContent=saved.has(selected.id)?'Đã lưu · Bỏ khỏi hành trình ♥':'Lưu vào hành trình ♡';get('detail-save').setAttribute('aria-pressed',String(saved.has(selected.id)));}
function showDetails(place){selected=place;get('detail-image').src=place.image;get('detail-image').alt=`Minh họa ${place.name}`;get('detail-tag').textContent=place.regionName.toUpperCase()+' / '+place.category.toUpperCase();get('detail-title').textContent=place.name;get('detail-description').textContent=place.description;get('detail-experiences').replaceChildren(...place.experiences.map(text=>node('li','',text)));get('detail-source').href=place.source;updateDetailSave();get('destination-dialog').showModal();}
function renderTrip(){const list=get('trip-list');list.replaceChildren();const places=[...saved].map(id=>destinations.find(place=>place.id===id)).filter(Boolean);if(!places.length)list.append(node('p','empty-trip','Hành trình đang đợi bạn. Bấm ♡ tại một điểm đến để lưu miền đất bạn muốn ghé.'));for(const place of places){const row=node('div','trip-item'),img=node('img');img.src=place.image;img.alt='';const info=node('div');info.append(node('strong','',place.name),node('small','',place.regionName+' · '+place.category));const remove=node('button','','×');remove.type='button';remove.setAttribute('aria-label','Bỏ '+place.name+' khỏi hành trình');remove.onclick=()=>toggleSave(place.id);row.append(img,info,remove);list.append(row);}get('download-trip').disabled=!places.length;}
function showTrip(){renderTrip();get('trip-dialog').showModal();}
get('open-trip').onclick=get('closing-trip').onclick=showTrip;get('detail-save').onclick=()=>toggleSave(selected.id);
get('download-trip').onclick=()=>{const text='HÀNH TRÌNH VIỆT NAM — ĐI ĐỂ THƯƠNG\n\n'+[...saved].map((id,index)=>{const p=destinations.find(place=>place.id===id);return `${index+1}. ${p.name}\n${p.intro}\nTìm hiểu: ${p.source}`;}).join('\n\n')+'\n\nDanh sách ý tưởng cá nhân; kiểm tra thông tin điểm đến trước khi lên đường.\n';const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=node('a');a.href=url;a.download='hanh-trinh-viet-nam.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Đã tải danh sách hành trình của bạn.');};
for(const button of document.querySelectorAll('[data-region]'))button.onclick=()=>{region=button.dataset.region;mood=null;document.querySelectorAll('[data-region]').forEach(el=>{el.classList.toggle('active',el===button);el.setAttribute('aria-pressed',String(el===button));});render();};
get('destination-search').oninput=render;for(const button of document.querySelectorAll('[data-mood]'))button.onclick=()=>{mood=button.dataset.mood;region='all';get('destination-search').value='';document.querySelectorAll('[data-region]').forEach(el=>{el.classList.toggle('active',el.dataset.region==='all');el.setAttribute('aria-pressed',String(el.dataset.region==='all'));});render();get('destinations').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});};
for(const button of document.querySelectorAll('[data-close]'))button.onclick=()=>get(button.dataset.close).close();
get('menu-toggle').onclick=()=>{const open=get('navigation').classList.toggle('open');get('menu-toggle').setAttribute('aria-expanded',String(open));};for(const link of get('navigation').querySelectorAll('a,button'))link.addEventListener('click',()=>{get('navigation').classList.remove('open');get('menu-toggle').setAttribute('aria-expanded','false');});
const scenes=[destinations[0],destinations[1],destinations[2]];get('next-scene').onclick=()=>{scene=(scene+1)%scenes.length;const place=scenes[scene];document.querySelector('.hero-art').style.backgroundImage=`url('${place.image}')`;get('hero-place').textContent=place.name;get('hero-caption').textContent=place.intro;get('scene-index').textContent=String(scene+1).padStart(2,'0');};
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}else document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));
persist();render();renderTrip();
